services:
    app:
        build:
            context: .
            dockerfile: _docker/php/Dockerfile
        container_name: laravel-app
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - db
        networks:
            - laravel

    nginx:
        image: nginx:stable
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: postgres:16
        container_name: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: laravel
            POSTGRES_DB: laravel
        volumes:
            - ./temp/db:/var/lib/postgresql/data
        networks:
            - laravel

networks:
    laravel:
